### ISSUE TITLE
Table Of Contents

### ISSUE THREAD

**Issue by dusual** [dusual/wayofdevops#1]
144 Hours

- [ ] Front Page #3 (1 hour)
- [ ] Preface #4  (3 hours)
- [ ] Table of Contents #1 (1 hour)
- - [ ] Introduction: [how things were, problems with it & How Devops solves some of the probs] (6 hours)
- - - [ ] Real World  Problem statement [ App to be taken through the points below till CD,  Case study of a company] (6 hours)
- - [ ] Operating System,  Processes & Resources 12 hours(1 week /2 hrs per day)
- - [ ] Abstraction & APIS & Protocols 12 hours(1 week /2 hrs per day)
- - [ ] Networking & Topologies( Physical Networks) 12 hours(1 week /2 hrs per day)
- - [ ] Protocols: TCP/IP,... 12 hours(1 week /2 hrs per day)
- - [ ] Virtualisation of Resources:  KVM, Virtual Box 12 hours(1 week /2 hrs per day)
- - [ ] Containorisation : Docker, Packer.... 12 hours(1 week /2 hrs per day)
- - [ ] Delivery - CI & CD 12 hours(1 week /2 hrs per day)
- - [ ] Upcoming Tech: Edge Computing, & Serverless & functions as a service(Cloud APIS) 12 hours(1 week /2 hrs per day)
- [ ] Cheat Sheet/Index #6 12 hours(1 week /2 hrs per day)
- [ ] Back Page #5 (2 hours)
